# 


# 





## Endpoints



# Group PortfolioWeb.ProjectController
## PortfolioWeb.ProjectController [/api/projects]
### PortfolioWeb.ProjectController index [GET /api/projects]


 


+ Request List all project
**GET**&nbsp;&nbsp;`/api/projects`

    + Headers
    
            accept: application/json

+ Response 200

    + Headers
    
            content-type: application/json; charset=utf-8
            cache-control: max-age=0, private, must-revalidate
            x-request-id: F55CTq788c7NAqkAAADl
    + Body
    
            {
              "data": [
                {
                  "body": "Quia voluptas quidem deserunt natus non ducimus ea aut. Tempore voluptatem non temporibus dicta? Officiis similique iusto molestiae tempora maiores et et distinctio! Veritatis cum consequatur molestiae reprehenderit aperiam rerum? Ipsam neque aut corporis et ipsa quam corrupti nihil.",
                  "id": 637,
                  "photo": "https://robohash.org/set_set2/bgset_bg1/X5MeKT0iAVfdvzEyORGN",
                  "slug": "rerum-rerum-nobis-sequi-quis-vero",
                  "summary": "Impedit dolorum soluta minima ipsa architecto fuga nulla! Quos at necessitatibus aut.",
                  "tags": [
                    {
                      "id": "elderberry",
                      "name": "Elderberry"
                    }
                  ],
                  "title": "Rerum rerum nobis sequi quis vero."
                },
                {
                  "body": "Ratione facilis consequatur sequi voluptatem qui. Quis dignissimos eum cum qui officiis. Quia et vel assumenda voluptatem est aut explicabo eius nesciunt. Dolores iusto quia repudiandae mollitia ratione nemo sequi. Debitis praesentium necessitatibus magnam accusantium.",
                  "id": 638,
                  "photo": "https://robohash.org/set_set1/bgset_bg1/9Y0IiETnIB4Wj0X88ZN",
                  "slug": "explicabo-quia-et-illo-praesentium-labore",
                  "summary": "Numquam neque quia ad? Eum quibusdam facilis rerum blanditiis cum quia dolore?",
                  "tags": [
                    {
                      "id": "mackerel",
                      "name": "Mackerel"
                    }
                  ],
                  "title": "Explicabo quia et illo praesentium labore."
                },
                {
                  "body": "Illum officia consequatur iste vitae totam. Sunt rerum neque deserunt autem laborum voluptatem sint! Minus sint saepe iure sit fugit? Ut ipsa veritatis fugiat! Voluptas rerum provident vel.",
                  "id": 634,
                  "photo": "https://robohash.org/set_set3/bgset_bg2/LLsMoxGs2GHj0kin7OHA",
                  "slug": "aspernatur-unde-quo-suscipit-voluptatum-ut",
                  "summary": "Esse labore ea facilis suscipit quia animi! Aut quasi eos error at qui impedit architecto rerum dolorem?",
                  "tags": [
                    {
                      "id": "mozzarella",
                      "name": "Mozzarella"
                    }
                  ],
                  "title": "Aspernatur unde quo suscipit voluptatum ut!"
                },
                {
                  "body": "Veniam eveniet at et! Facilis sunt reprehenderit laudantium est voluptatum ex quisquam dolor. Modi beatae ea voluptatibus veniam. Culpa porro cumque dolor nisi. Minima officia modi nulla vero beatae dolorem.",
                  "id": 635,
                  "photo": "https://robohash.org/set_set1/bgset_bg2/oTrlZ9V8PqTlxlCa01",
                  "slug": "consectetur-laudantium-aperiam-et-ratione-ad",
                  "summary": "Nostrum quae est qui cum aut consequuntur et velit? Nam non dolor quisquam voluptas.",
                  "tags": [
                    {
                      "id": "liver",
                      "name": "Liver"
                    }
                  ],
                  "title": "Consectetur laudantium aperiam et ratione ad."
                },
                {
                  "body": "Excepturi sunt rem doloremque in commodi soluta. Ipsum iure eum culpa? Perferendis error blanditiis nobis? Voluptatum illum autem in vitae harum numquam assumenda. Et distinctio dolorem minima id.",
                  "id": 636,
                  "photo": "https://robohash.org/set_set3/bgset_bg1/Oc8NXMadJTUrv4DHs",
                  "slug": "asperiores-sit-ipsam-qui-qui",
                  "summary": "Ad ut cumque repellat cumque. Ut architecto ut enim.",
                  "tags": [
                    {
                      "id": "chestnut",
                      "name": "Chestnut"
                    }
                  ],
                  "title": "Asperiores sit ipsam qui qui?"
                }
              ]
            }
### PortfolioWeb.ProjectController show_slug [GET /api/projects/slug/{slug}]


 

+ Parameters
    + slug: `quia-rerum-temporibus-dolorem-voluptatibus-odit-saepe-non-distinctio`
            slug: quia-rerum-temporibus-dolorem-voluptatibus-odit-saepe-non-distinctio


+ Request Get project by slug
**GET**&nbsp;&nbsp;`/api/projects/slug/quia-rerum-temporibus-dolorem-voluptatibus-odit-saepe-non-distinctio`

    + Headers
    
            accept: application/json

+ Response 200

    + Headers
    
            content-type: application/json; charset=utf-8
            cache-control: max-age=0, private, must-revalidate
            x-request-id: F55CTq9A1aNHp24AAAPB
    + Body
    
            {
              "body": "Dolor laudantium expedita veniam recusandae voluptas qui nihil. Architecto qui qui aspernatur iste minima temporibus voluptatem quo! Libero neque iusto occaecati id. Nemo molestias quod quos quo provident minus aut odit accusamus. Et omnis qui quos officiis illo sunt commodi.",
              "id": 639,
              "photo": "https://robohash.org/set_set1/bgset_bg2/f",
              "slug": "quia-rerum-temporibus-dolorem-voluptatibus-odit-saepe-non-distinctio",
              "summary": "Rerum consectetur nihil enim blanditiis quam et veritatis? Et dolore soluta eum aut velit ut odit?",
              "tags": [
                {
                  "id": "soba",
                  "name": "Soba"
                }
              ],
              "title": "Quia rerum temporibus dolorem voluptatibus odit saepe non distinctio."
            }
### PortfolioWeb.ProjectController update [PUT /api/projects/{id}]


 

+ Parameters
    + id: `629`
            id: 629


+ Request Update project fail
**PUT**&nbsp;&nbsp;`/api/projects/629`

    + Headers
    
            accept: application/json
            content-type: multipart/mixed; boundary=plug_conn_test
    + Body
    
            {
              "project": {
                "body": null,
                "photo": null,
                "slug": null,
                "summary": null,
                "title": null
              }
            }

+ Response 422

    + Headers
    
            content-type: application/json; charset=utf-8
            cache-control: max-age=0, private, must-revalidate
            x-request-id: F55CTqtB44xYKgkAAAMh
    + Body
    
            {
              "errors": {
                "body": [
                  "can't be blank"
                ],
                "photo": [
                  "can't be blank"
                ],
                "slug": [
                  "can't be blank"
                ],
                "summary": [
                  "can't be blank"
                ],
                "title": [
                  "can't be blank"
                ]
              }
            }
### PortfolioWeb.ProjectController create [POST /api/projects]


 


+ Request Create project
**POST**&nbsp;&nbsp;`/api/projects`

    + Headers
    
            accept: application/json
            content-type: multipart/mixed; boundary=plug_conn_test
    + Body
    
            {
              "project": {
                "body": "some body",
                "photo": "some photo",
                "slug": "some slug",
                "summary": "some summary",
                "tags": "Backend, Frontend",
                "title": "some title"
              }
            }

+ Response 201

    + Headers
    
            content-type: application/json; charset=utf-8
            cache-control: max-age=0, private, must-revalidate
            x-request-id: F55CTq1hYJi2DEQAAABF
            location: /api/projects/631
    + Body
    
            {
              "data": {
                "body": "some body",
                "id": 631,
                "photo": "some photo",
                "slug": "some slug",
                "summary": "some summary",
                "tags": [
                  {
                    "id": "backend",
                    "name": "Backend"
                  },
                  {
                    "id": "frontend",
                    "name": "Frontend"
                  }
                ],
                "title": "some title"
              }
            }


+ Request Create project fail
**POST**&nbsp;&nbsp;`/api/projects`

    + Headers
    
            accept: application/json
            content-type: multipart/mixed; boundary=plug_conn_test
    + Body
    
            {
              "project": {
                "body": null,
                "photo": null,
                "slug": null,
                "summary": null,
                "title": null
              }
            }

+ Response 422

    + Headers
    
            content-type: application/json; charset=utf-8
            cache-control: max-age=0, private, must-revalidate
            x-request-id: F55CTrAFGLQjrEsAAARB
    + Body
    
            {
              "errors": {
                "body": [
                  "can't be blank"
                ],
                "photo": [
                  "can't be blank"
                ],
                "slug": [
                  "can't be blank"
                ],
                "summary": [
                  "can't be blank"
                ],
                "title": [
                  "can't be blank"
                ]
              }
            }
### PortfolioWeb.ProjectController update [PUT /api/projects/{id}]


 

+ Parameters
    + id: `630`
            id: 630


+ Request Update project
**PUT**&nbsp;&nbsp;`/api/projects/633`

    + Headers
    
            accept: application/json
            content-type: multipart/mixed; boundary=plug_conn_test
    + Body
    
            {
              "project": {
                "body": "some updated body",
                "photo": "some updated photo",
                "slug": "some updated slug",
                "summary": "some updated summary",
                "tags": "New, New tag",
                "title": "some updated title"
              }
            }

+ Response 200

    + Headers
    
            content-type: application/json; charset=utf-8
            cache-control: max-age=0, private, must-revalidate
            x-request-id: F55CTq5NSgcB5CYAAACF
    + Body
    
            {
              "data": {
                "body": "some updated body",
                "id": 633,
                "photo": "some updated photo",
                "slug": "some updated slug",
                "summary": "some updated summary",
                "tags": [
                  {
                    "id": "new",
                    "name": "New"
                  },
                  {
                    "id": "new-tag",
                    "name": "New tag"
                  }
                ],
                "title": "some updated title"
              }
            }


+ Request Update project fail
**PUT**&nbsp;&nbsp;`/api/projects/630`

    + Headers
    
            accept: application/json
            content-type: multipart/mixed; boundary=plug_conn_test
    + Body
    
            {
              "project": {
                "body": null,
                "photo": null,
                "slug": null,
                "summary": null,
                "title": null
              }
            }

+ Response 422

    + Headers
    
            content-type: application/json; charset=utf-8
            cache-control: max-age=0, private, must-revalidate
            x-request-id: F55CTq0-rufl1QQAAAAl
    + Body
    
            {
              "errors": {
                "body": [
                  "can't be blank"
                ],
                "photo": [
                  "can't be blank"
                ],
                "slug": [
                  "can't be blank"
                ],
                "summary": [
                  "can't be blank"
                ],
                "title": [
                  "can't be blank"
                ]
              }
            }

